// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmhTxoO9WZbb_odEVrRMmfkpXXZ5-QaaQ',
    appId: '1:259377931534:web:ae6c6eb05045d2f256635f',
    messagingSenderId: '259377931534',
    projectId: 'my-project-a18ad',
    authDomain: 'my-project-a18ad.firebaseapp.com',
    storageBucket: 'my-project-a18ad.firebasestorage.app',
    measurementId: 'G-T6WR3LZ5EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5LuNGO_LT-c0HnVGpQqnI4f-FJz4118',
    appId: '1:259377931534:android:89ea573badb7227856635f',
    messagingSenderId: '259377931534',
    projectId: 'my-project-a18ad',
    storageBucket: 'my-project-a18ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA77nPe83axzjyHQSyZjbaPEv2flZBW20',
    appId: '1:259377931534:ios:8252b3d38a161e7656635f',
    messagingSenderId: '259377931534',
    projectId: 'my-project-a18ad',
    storageBucket: 'my-project-a18ad.firebasestorage.app',
    iosClientId: '259377931534-jj2ldimbjlpjlvc9n5hborjt7head14l.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacecourseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA77nPe83axzjyHQSyZjbaPEv2flZBW20',
    appId: '1:259377931534:ios:8252b3d38a161e7656635f',
    messagingSenderId: '259377931534',
    projectId: 'my-project-a18ad',
    storageBucket: 'my-project-a18ad.firebasestorage.app',
    iosClientId: '259377931534-jj2ldimbjlpjlvc9n5hborjt7head14l.apps.googleusercontent.com',
    iosBundleId: 'com.example.spacecourseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmhTxoO9WZbb_odEVrRMmfkpXXZ5-QaaQ',
    appId: '1:259377931534:web:a4a278f96077202f56635f',
    messagingSenderId: '259377931534',
    projectId: 'my-project-a18ad',
    authDomain: 'my-project-a18ad.firebaseapp.com',
    storageBucket: 'my-project-a18ad.firebasestorage.app',
    measurementId: 'G-HS0N4550ND',
  );
}
